---
title: 'Getting Started'
output: html_notebook
---

# Cereal Sales

## Accessing Data

```{r setup}
library(ggthemes)
library(readr)
library(GGally)
library(gridExtra)
library(kableExtra)
library(tidyverse)
library(GGally)
library(pins)
```


Next, we'll import and join the 2 datasets.

```{r mtp}
# Load Data

MTP_Data <- read_csv("MTP_Data.csv")
mtp_data2 <- read_csv("mtp_data2.csv")

mtp <- mtp_data2 %>% left_join(MTP_Data)

#Initial Review of the data
glimpse(mtp)
```

Using our imported data, we can pull only the KELLOGGS data.

```{r pull-data}

mtp_prepped <- mtp %>% separate(brand, into = c("company", "brand"), sep = "\\ ", extra = "merge") %>% 
  mutate(company =  recode(company, "GENERAL" = "GENERAL MILLS")) %>% mutate(promo = factor(promo), 
         promo = recode(promo, "0" = "No Promo", "1" = "Promo"),
         ad =  recode(ad, "NONE" = "No Ad", "A" = "Big Ad", "B" = "Mid/Small Ad"),
         brand =  recode(brand,  "MILLS CINNAMON TST CR" = "CINNAMON TST CR",
                                 "MILLS CHEERIOS" = "CHEERIOS",
                                 "MILLS LUCKY CHARMS" = "LUCKY CHARMS",
                                 "MILLS COCOA PUFFS" = "COCOA PUFFS",
                                 "MILLS KIX" = "KIX"),
         TotalSale = units*price,
         TotalVolume = units*volume)

#review the updated data
glimpse(mtp_prepped)

distinct(mtp_prepped, brand)


company_name <- "KELLOGGS"


mtp_KELLOGGS <- filter(mtp_prepped, company == company_name )

mtp_KELLOGGS %>% write_csv("mtp_KELLOGGS.csv")

```

Publish Pin
```{r}
pins::board_register_rsconnect()


read_csv('mtp_KELLOGGS.csv') %>% pin("mtp_KELLOGGS", description = "KELLOGGS Daily Sales", board = "rsconnect")
```


## Plotting

Now we're ready to start investigating the data and showing off the resulting graphics. We'll create plots and then a static dashboard.

```{r plots}
mtp_KELLOGGS %>% 
  group_by(brand) %>% 
  summarise(units = sum(units)) %>% 
  ggplot() +
  geom_bar(aes(reorder(brand,units), units), stat = 'identity') +
  coord_flip() +
  labs(
    title = company_name,
    x = NULL,
    y = NULL
  ) +
  theme_minimal()
```

```{r gender}
  # plot by gender
ggplot(mtp_KELLOGGS) +
  geom_bar(aes(reorder(brand,units), units, fill = flavor), stat = 'identity') +
  facet_wrap(~flavor)+
  coord_flip() +
  labs(
    title = company_name,
    x = NULL,
    y = NULL
  ) +
  theme_minimal() + 
  guides(fill = FALSE) + 
  scale_fill_manual(values = c("#d54a30","#4c83b6", "#d0d530", "#9030d5"))

```
