---
title: "Adverse Events"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    theme: readable
    vertical_layout: fill
---


```{r setup, include=FALSE}
library(ggthemes)
library(readr)
library(GGally)
library(gridExtra)
library(kableExtra)
library(tidyverse)
library(GGally)

# Load Data

MTP_Data <- read_csv("MTP_Data.csv")
mtp_data2 <- read_csv("mtp_data2.csv")

mtp <- mtp_data2 %>% left_join(MTP_Data)

```

```{r}

# Clean Data
mtp_prepped <- mtp %>% separate(brand, into = c("company", "brand"), sep = "\\ ", extra = "merge") %>% 
  mutate(company =  recode(company, "GENERAL" = "GENERAL MILLS")) %>% mutate(promo = factor(promo), 
         promo = recode(promo, "0" = "No Promo", "1" = "Promo"),
         ad =  recode(ad, "NONE" = "No Ad", "A" = "Big Ad", "B" = "Mid/Small Ad"),
         brand =  recode(brand,  "MILLS CINNAMON TST CR" = "CINNAMON TST CR",
                                 "MILLS CHEERIOS" = "CHEERIOS",
                                 "MILLS LUCKY CHARMS" = "LUCKY CHARMS",
                                 "MILLS COCOA PUFFS" = "COCOA PUFFS",
                                 "MILLS KIX" = "KIX"),
         TotalSale = units*price,
         TotalVolume = units*volume)

#review the updated data
glimpse(mtp_prepped)

distinct(mtp_prepped, brand)

# create_price <- function(min, max){# sprintf('[%f+TO+%f]', min, max)}

company_name <- "KELLOGGS"



# specify age range
# price2 <- create_price(.5,2)


mtp_KELLOGGS <- filter(mtp_prepped, company == company_name )

```


Column 
-----------------------------------------------------------------------

### All Events


```{r}

```

Column 
-----------------------------------------------------------------------

### Age Range

```{r}

```


### Events by Gender 

```{r}

```
