---
title: "Cereal Sales"
resource_files:
- .httr-oauth .Renviron
- .httr-oauth
- .Renviron
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    css: styles.css
    orientation: columns
    theme: readable
    vertical_layout: fill
---



```{r setup, include=FALSE}
library(ggthemes)
library(readr)
library(GGally)
library(gridExtra)
library(kableExtra)
library(tidyverse)
library(GGally)
library(flexdashboard)

# Load Data

MTP_Data <- read_csv("MTP_Data.csv")
mtp_data2 <- read_csv("mtp_data2.csv")

mtp <- mtp_data2 %>% left_join(MTP_Data)

# Clean Data
mtp_prepped <- mtp %>% separate(brand, into = c("company", "brand"), sep = "\\ ", extra = "merge") %>% 
  mutate(company =  recode(company, "GENERAL" = "GENERAL MILLS")) %>% mutate(promo = factor(promo), 
         promo = recode(promo, "0" = "No Promo", "1" = "Promo"),
         ad =  recode(ad, "NONE" = "No Ad", "A" = "Big Ad", "B" = "Mid/Small Ad"),
         brand =  recode(brand,  "MILLS CINNAMON TST CR" = "CINNAMON TST CR",
                                 "MILLS CHEERIOS" = "CHEERIOS",
                                 "MILLS LUCKY CHARMS" = "LUCKY CHARMS",
                                 "MILLS COCOA PUFFS" = "COCOA PUFFS",
                                 "MILLS KIX" = "KIX"),
         TotalSale = units*price,
         TotalVolume = units*volume)
  


```

Column {.sidebar}
------------

```{r inputs}


textInput('sel_name', 'Brand Name Drug', value = "KELLOGGS")

sliderInput('week', 
            'Week Range',
            min = min(mtp_prepped$week), 
            max = max(mtp_prepped$week),
            value = c(1490, 1515))

mtp_sel <- reactive({ 
  mtp_prepped %>% 
    filter(company == input$sel_name,
           week >= input$week[1],
           week <= input$week[2])

})


```

Column {data-width=650}
-----------------------------------------------------------------------

### Time Horizon

```{r}
time_label <- reactive({
  sprintf("%d to %d", input$week[1], input$week[2])
})
renderValueBox({valueBox(time_label(), icon = 'glyphicon-cal')})
```


### All Sales

```{r}
renderPlot({
  req(mtp_sel())
  mtp_sel() %>% 
  group_by(brand) %>% 
   summarise(units = sum(units)) %>% 
  ggplot() +
  geom_bar(aes(reorder(brand,units), units), stat = 'identity') +
    coord_flip() +
    labs(
      title = input$sel_name,
      x = NULL,
      y = NULL
    ) +
    theme_minimal()
})


```



Column {data-width=350}
-----------------------------------------------------------------------



### Sales by Flavor

```{r}
renderPlot({
  req(mtp_sel())
  ggplot(mtp_sel()) +
    geom_bar(aes(reorder(brand,units), units, fill = flavor), stat = 'identity') +
    facet_wrap(~flavor)+
    coord_flip() +
    labs(
      title = input$sel_name,
      x = NULL,
      y = NULL
    ) +
    theme_minimal() + 
    guides(fill = FALSE) + 
  scale_fill_manual(values = c("#d54a30","#4c83b6", "#d0d530", "#9030d5"))

})
```


### Sales by Promo

```{r}
renderPlot({
  req(mtp_sel())
  ggplot(mtp_sel()) +
    geom_bar(aes(reorder(brand,units), units, fill = promo), stat = 'identity') +
    facet_wrap(~promo)+
    coord_flip() +
    labs(
      title = input$sel_name,
      x = NULL,
      y = NULL
    ) +
    theme_minimal() + 
    guides(fill = FALSE) + 
  scale_fill_manual(values = c("#d54a30","#4c83b6", "#d0d530", "#9030d5"))

})
```
